#!/usr/bin/env bash

DOTFILES_HOME=$HOME/.dotfiles

print_header() {
  printf "\e[34m"
  echo '------------------------------------------------------------------'
  echo '                      __      __  _____ __                        '
  echo '                 ____/ /___  / /_/ __(_) /__  _____               '
  echo '                / __  / __ \/ __/ /_/ / / _ \/ ___/               '
  echo '               / /_/ / /_/ / /_/ __/ / /  __(__  )                '
  echo '               \__,_/\____/\__/_/ /_/_/\___/____/                 '
  echo '                                                                  '
  echo '                Harder, Better, Faster, Stronger                  '
  echo '                                                                  '
  echo '                  github.com/matsuosh/dotfiles                    '
  echo '                                                                  '
  echo '------------------------------------------------------------------'
  printf "\e[0m\n"
}

make_links() {

  # Git
  SRC_DIR=$DOTFILES_HOME/git
  for file in $(ls -1 $SRC_DIR);
  do
    echo "ln -s -f $SRC_DIR/$file $HOME/.$file"
    ln -s -f $SRC_DIR/$file $HOME/.$file
  done

  # Vim
  SRC_DIR=$DOTFILES_HOME/vim
  echo "ln -s -f $SRC_DIR/vimrc $HOME/.vimrc"
  ln -s -f $SRC_DIR/vimrc $HOME/.vimrc
  if [ ! -d $HOME/.vim ]; then
    echo "ln -s -f $SRC_DIR/vim $HOME/.vim"
    ln -s -f $SRC_DIR/vim $HOME/.vim
  fi
  
  grep 'source $HOME/.dotfiles/bash/bashrc' $HOME/.bashrc > /dev/null
  if [ $? -ne 0 ]; then
    echo 'source $HOME/.dotfiles/bash/bashrc >> $HOME/.bashrc'
    echo 'source $HOME/.dotfiles/bash/bashrc' >> $HOME/.bashrc
  fi

}

main() {
  print_header
  make_links
}

main
