set nocompatible              " be iMproved, required
filetype off                  " required

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'

Plugin 'tomtom/tcomment_vim'
Plugin 'Valloric/YouCompleteMe'
Plugin 'ctrlpvim/ctrlp.vim'
Plugin 'sheerun/vim-polyglot'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-endwise'
Plugin 'thinca/vim-ref'
Plugin 'yuku-t/vim-ref-ri'
Plugin 'szw/vim-tags'
Plugin 'lilydjwg/colorizer'
Plugin 'zenorocha/dracula-theme', {'rtp': 'vim/'}

source ~/.vim/syntastic.vim
source ~/.vim/indentline.vim
source ~/.vim/nerdtree.vim


call vundle#end()
filetype plugin indent on

syntax on
color dracula

set encoding     =utf-8             " エンコード
set fileencoding =utf-8             " ファイルのエンコード

set noswapfile                      " .swapファイルを作らない
set nowritebackup                   " バックアップファイルを作らない
set nobackup                        " バックアップをしない

set autoindent                      " オートインデント
set shiftwidth   =2                 " インデントにしたときのスペースの文字数
set expandtab                       " タブをスペースにする
set softtabstop  =2                 " タブをスペースにするときの文字数
set shiftround                      " インデントをオプション 'shiftwidth' の値の倍数に丸める。 コマンド \">\"と \"<\" に適用される。Insertモードでの CTRL-T と CTRL-D では、インデントは常に 'shiftwidth' の倍数に丸められる

set backspace    =indent,eol,start  " Make backspace work as you would expect.
set hidden                          " Switch between buffers without having to save first.
set laststatus   =2                 " Always show statusline.
set display      =lastline          " Show as much as possible of the last line.

set showmatch                       " 括弧のハイライト

" 検索
set incsearch                       " Highlight while searching with / or ?.
set ignorecase
set smartcase
set hlsearch                        " Keep matches highlighted.

set mouse       =a                  " マウスモード

set number                          " 行番号
set vb t_vb     =                   " ビープ音
set novisualbell

" Vim wiki
" http://vimwiki.net/?FrontPage

" Powerline
source ~/.vim/powerline.vim

augroup MyXML
  autocmd!
  autocmd Filetype xml inoremap <buffer> </ </<C-x><C-o>
  autocmd Filetype html inoremap <buffer> </ </<C-x><C-o>
  autocmd Filetype eruby inoremap <buffer> </ </<C-x><C-o>
augroup END
