if &compatible
  set nocompatible
endif

" Required:
set runtimepath^=~/.vim/bundle/neobundle.vim/

" Required:
call neobundle#begin(expand('~/.vim/bundle'))

" Let NeoBundle manage NeoBundle
" Required:
NeoBundleFetch 'Shougo/neobundle.vim'

" Add or remove your Bundles here:
"NeoBundle 'Shougo/neosnippet.vim'
"NeoBundle 'Shougo/neosnippet-snippets'
"NeoBundle 'tpope/vim-fugitive'

" http://qiita.com/oahiroaki/items/d71337fb9d28303a54a8
NeoBundle 'ctrlpvim/ctrlp.vim'
"NeoBundle 'flazz/vim-colorschemes'

" コード補完
"source ~/.vim/neocomplete.vim

" シンタックス
NeoBundle 'sheerun/vim-polyglot'

" 静的解析
source ~/.vim/syntastic.vim

" HTML
NeoBundle 'tpope/vim-surround'
" 自動で閉じる
NeoBundle 'tpope/vim-endwise'

" インデント
NeoBundle 'Yggdroot/indentLine'
let g:indentLine_char = '·'
let g:indentLine_char = '˖'
let g:indentLine_color_term = 240

" ドキュメント参照
NeoBundle 'thinca/vim-ref'
NeoBundle 'yuku-t/vim-ref-ri'

" メソッド定義元へのジャンプ
NeoBundle 'szw/vim-tags'

" NERDTree
source ~/.vim/nerdtree.vim

"----------------------------
" テーマ
"----------------------------
NeoBundle 'zenorocha/dracula-theme', {'rtp': 'vim/'}







" You can specify revision/branch/tag.
NeoBundle 'Shougo/vimshell', { 'rev' : '3787e5' }

" Required:
call neobundle#end()

" Required:
filetype plugin indent on

" If there are uninstalled bundles found on startup,
" this will conveniently prompt you to install them.
NeoBundleCheck

syntax on
color dracula

set encoding     =utf-8             " エンコード
set fileencoding =utf-8             " ファイルのエンコード

set noswapfile                      " .swapファイルを作らない
set nowritebackup                   " バックアップファイルを作らない
set nobackup                        " バックアップをしない

set autoindent                      " オートインデント
set shiftwidth   =2                 " インデントにしたときのスペースの文字数
set expandtab                       " タブをスペースにする
set softtabstop  =2                 " タブをスペースにするときの文字数
set shiftround                      " インデントをオプション 'shiftwidth' の値の倍数に丸める。 コマンド \">\"と \"<\" に適用される。Insertモードでの CTRL-T と CTRL-D では、インデントは常に 'shiftwidth' の倍数に丸められる

set backspace    =indent,eol,start  " Make backspace work as you would expect.
set hidden                          " Switch between buffers without having to save first.
set laststatus   =2                 " Always show statusline.
set display      =lastline          " Show as much as possible of the last line.

set showmatch                       " 括弧のハイライト

" 検索
set incsearch                       " Highlight while searching with / or ?.
set ignorecase
set smartcase
set hlsearch                        " Keep matches highlighted.

set mouse       =a                  " マウスモード

set number                          " 行番号
set vb t_vb     =                   " ビープ音
set novisualbell

" Vim wiki
" http://vimwiki.net/?FrontPage

" Powerline
source ~/.vim/powerline.vim

