# bash-completion
if [ -f /usr/local/etc/bash_completion ]
then
  . /usr/local/etc/bash_completion
fi

# python
if [ -d /usr/local/opt/python/libexec/bin ]
then
  export PATH="/usr/local/opt/python/libexec/bin:$PATH"
fi

# nvm
if [ -d $HOME/.nvm ]
then
  export NVM_DIR="$HOME/.nvm"
  . "/usr/local/opt/nvm/nvm.sh"
fi

# rbenv
if [ $(which rbenv) ]
then
  eval "$(rbenv init -)"
fi

# powerline
powerline-daemon -q
POWERLINE_BASH_CONTINUATION=1
POWERLINE_BASH_SELECT=1
. /usr/local/lib/python2.7/site-packages/powerline/bindings/bash/powerline.sh

# alias
alias ls='ls -G'
alias ll='ls -l'
alias la='ll -a'
alias h='history'
alias c='clear'
