# Starship prompt configuration
# https://starship.rs/config/

[aws]
disabled = true

[gcloud]
disabled = true

[nodejs]
disabled = true

[python]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true
